In [46]:
import pandas as pd
df = pd.read_parquet("../data/yellow_tripdata_2025-01.parquet")
df = df[df["payment_type"].isin([1, 2])]
df = df[df["fare_amount"] >= 3]
df["duration_min"] = (df["tpep_dropoff_datetime"] - df["tpep_pickup_datetime"]).dt.total_seconds() / 60
df = df[df["duration_min"] >= 1]
len(df)

2796745

In [47]:
df.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,duration_min
count,2.796745e+06,2796745,2796745,2.796745e+06,2.796745e+06,2.796745e+06,2.796745e+06,2.796745e+06,2.796745e+06,2.796745e+06,2.796745e+06,2.796745e+06,2.796745e+06,2.796745e+06,2.796745e+06,2.796745e+06,2.796745e+06,2.796745e+06,2.796745e+06,2.796745e+06
mean,1.768214e+00,2025-01-17 02:51:12.284478,2025-01-17 03:06:21.898889,1.294797e+00,3.210124e+00,2.516937e+00,1.671686e+02,1.662602e+02,1.131336e+00,1.785630e+01,1.613689e+00,4.962252e-01,3.547676e+00,5.230165e-01,9.870235e-01,2.732911e+01,2.328388e+00,1.294237e-01,4.880722e-01,1.516024e+01
min,1.000000e+00,2024-12-31 20:47:55,2024-12-31 20:54:00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
25%,2.000000e+00,2025-01-09 16:41:10,2025-01-09 16:57:42,1.000000e+00,9.900000e-01,1.000000e+00,1.320000e+02,1.160000e+02,1.000000e+00,8.600000e+00,0.000000e+00,5.000000e-01,1.500000e+00,0.000000e+00,1.000000e+00,1.596000e+01,2.500000e+00,0.000000e+00,0.000000e+00,7.116667e+00
50%,2.000000e+00,2025-01-16 21:14:48,2025-01-16 21:29:01,1.000000e+00,1.620000e+00,1.000000e+00,1.620000e+02,1.630000e+02,1.000000e+00,1.210000e+01,1.000000e+00,5.000000e-01,2.950000e+00,0.000000e+00,1.000000e+00,2.040000e+01,2.500000e+00,0.000000e+00,7.500000e-01,1.138333e+01
75%,2.000000e+00,2025-01-24 17:35:35,2025-01-24 17:51:47,1.000000e+00,3.000000e+00,1.000000e+00,2.340000e+02,2.360000e+02,1.000000e+00,1.910000e+01,2.500000e+00,5.000000e-01,4.290000e+00,0.000000e+00,1.000000e+00,2.840000e+01,2.500000e+00,0.000000e+00,7.500000e-01,1.816667e+01
max,2.000000e+00,2025-02-01 00:00:44,2025-02-01 23:44:11,9.000000e+00,4.473030e+04,9.900000e+01,2.650000e+02,2.650000e+02,2.000000e+00,2.450900e+03,1.500000e+01,6.500000e+00,4.000000e+02,1.709400e+02,1.000000e+00,2.506710e+03,2.500000e+00,1.750000e+00,7.500000e-01,5.626317e+03
std,4.219733e-01,NaN,NaN,7.486754e-01,4.364565e+01,1.185814e+01,6.299784e+01,6.884912e+01,3.377678e-01,1.689458e+01,1.903125e+00,4.368945e-02,3.820207e+00,2.083207e+00,1.131730e-01,2.135686e+01,6.321230e-01,4.579744e-01,3.575468e-01,2.932938e+01

In [48]:
df[(df["duration_min"] < 5) & (df["total_amount"] > 10)]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,duration_min
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,...,3.50,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.00,2.550000
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,...,3.50,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.00,1.950000
6,1,2025-01-01 00:14:47,2025-01-01 00:16:15,0.0,0.40,1.0,N,170,170,1,...,3.50,0.5,2.35,0.0,1.0,11.75,2.5,0.0,0.00,1.466667
11,2,2025-01-01 00:33:58,2025-01-01 00:37:23,1.0,0.56,1.0,N,263,236,1,...,1.00,0.5,2.16,0.0,1.0,12.96,2.5,0.0,0.00,3.416667
29,2,2025-01-01 00:00:37,2025-01-01 00:04:46,1.0,0.86,1.0,N,140,263,2,...,1.00,0.5,0.00,0.0,1.0,11.50,2.5,0.0,0.00,4.150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2935034,2,2025-01-31 23:01:16,2025-01-31 23:03:33,1.0,0.21,1.0,N,79,79,2,...,1.00,0.5,0.00,0.0,1.0,10.15,2.5,0.0,0.75,2.283333
2935051,2,2025-01-31 23:04:31,2025-01-31 23:08:44,1.0,0.60,1.0,N,79,224,1,...,1.00,0.5,3.06,0.0,1.0,15.31,2.5,0.0,0.75,4.216667
2935059,2,2025-01-31 23:39:46,2025-01-31 23:44:42,1.0,0.76,1.0,N,107,100,1,...,1.00,0.5,2.45,0.0,1.0,14.70,2.5,0.0,0.75,4.933333
2935071,2,2025-01-31 23:52:52,2025-01-31 23:57:42,1.0,0.96,1.0,N,141,236,1,...,1.00,0.5,2.44,0.0,1.0,14.64,2.5,0.0,0.00,4.833333
2935073,1,2025-01-31 23:11:28,2025-01-31 23:14:45,1.0,0.60,1.0,N,48,48,2,...,4.25,0.5,0.00,0.0,1.0,10.85,2.5,0.0,0.75,3.283333